# Generated by Django 3.1.4 on 2021-04-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=10)),
                ('catalog_number', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=100)),
                ('course_type', models.CharField(max_length=20)),
                ('dates', models.CharField(max_length=100)),
                ('credit', models.CharField(max_length=20)),
                ('meeting_time', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField(null=True)),
                ('seats_taken', models.IntegerField(null=True)),
                ('seats_available', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['subject'],
            },
        ),
    ]
